// <auto-generated />
using CoraCorpCM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoraCorpCM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180114014044_AddsDbSets")]
    partial class AddsDbSets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoraCorpCM.Models.Acquisition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Cost");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("FundingSourceId");

                    b.Property<int?>("LocationId");

                    b.Property<int?>("MuseumId");

                    b.Property<int?>("PieceSourceId");

                    b.Property<int?>("PurchaseReceiptId");

                    b.Property<string>("Terms");

                    b.HasKey("Id");

                    b.HasIndex("FundingSourceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("MuseumId");

                    b.HasIndex("PieceSourceId");

                    b.HasIndex("PurchaseReceiptId");

                    b.ToTable("Acquisitions");
                });

            modelBuilder.Entity("CoraCorpCM.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<int?>("MuseumId");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("date");

                    b.Property<DateTime>("Deathdate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName");

                    b.Property<string>("KnownAs");

                    b.Property<string>("LastName");

                    b.Property<int?>("MuseumId");

                    b.Property<int?>("OriginId");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.HasIndex("OriginId");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("CoraCorpCM.Models.ArtistGenre", b =>
                {
                    b.Property<int>("ArtistId");

                    b.Property<int>("GenreId");

                    b.HasKey("ArtistId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ArtistGenre");
                });

            modelBuilder.Entity("CoraCorpCM.Models.ArtistMedium", b =>
                {
                    b.Property<int>("ArtistId");

                    b.Property<int>("MediumId");

                    b.HasKey("ArtistId", "MediumId");

                    b.HasIndex("MediumId");

                    b.ToTable("ArtistMedium");
                });

            modelBuilder.Entity("CoraCorpCM.Models.ArtistSubgenre", b =>
                {
                    b.Property<int>("ArtistId");

                    b.Property<int>("SubgenreId");

                    b.HasKey("ArtistId", "SubgenreId");

                    b.HasIndex("SubgenreId");

                    b.ToTable("ArtistSubgenre");
                });

            modelBuilder.Entity("CoraCorpCM.Models.ArtistSubjectMatter", b =>
                {
                    b.Property<int>("ArtistId");

                    b.Property<int>("SubjectMatterId");

                    b.HasKey("ArtistId", "SubjectMatterId");

                    b.HasIndex("SubjectMatterId");

                    b.ToTable("ArtistSubjectMatter");
                });

            modelBuilder.Entity("CoraCorpCM.Models.ArtistTag", b =>
                {
                    b.Property<int>("ArtistId");

                    b.Property<int>("TagId");

                    b.HasKey("ArtistId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArtistTag");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MuseumId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int?>("MuseumId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.ToTable("Condition");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Country", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Genc2A")
                        .HasMaxLength(2);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Exhibition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Curator");

                    b.Property<DateTime>("EndDate");

                    b.Property<int?>("LocationId");

                    b.Property<int?>("MuseumId");

                    b.Property<string>("Name");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Theme");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("MuseumId");

                    b.ToTable("Exhibition");
                });

            modelBuilder.Entity("CoraCorpCM.Models.ExhibitionPiece", b =>
                {
                    b.Property<int>("ExhibitionId");

                    b.Property<int>("PieceId");

                    b.HasKey("ExhibitionId", "PieceId");

                    b.HasIndex("PieceId");

                    b.ToTable("ExhibitionPiece");
                });

            modelBuilder.Entity("CoraCorpCM.Models.FundingSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MuseumId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.ToTable("FundingSources");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MuseumId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ConditionId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("InspectorId");

                    b.Property<int?>("MuseumId");

                    b.Property<string>("Notes");

                    b.Property<int?>("PieceId");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.HasIndex("InspectorId");

                    b.HasIndex("MuseumId");

                    b.HasIndex("PieceId");

                    b.ToTable("Inspection");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Inspector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("KnownAs");

                    b.Property<string>("LastName");

                    b.Property<int?>("MuseumId");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.ToTable("Inspector");
                });

            modelBuilder.Entity("CoraCorpCM.Models.InsurancePolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("AmountInsured");

                    b.Property<string>("Carrier");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int?>("MuseumId");

                    b.Property<string>("PolicyNumber");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.ToTable("InsurancePolicies");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ExhibitionId");

                    b.Property<DateTime>("FromDate");

                    b.Property<int?>("FromLocationId");

                    b.Property<int?>("LoanAgreementId");

                    b.Property<int?>("MuseumId");

                    b.Property<string>("Terms");

                    b.Property<DateTime>("ToDate");

                    b.Property<int?>("ToLocationId");

                    b.HasKey("Id");

                    b.HasIndex("ExhibitionId");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("LoanAgreementId");

                    b.HasIndex("MuseumId");

                    b.HasIndex("ToLocationId");

                    b.ToTable("Loan");
                });

            modelBuilder.Entity("CoraCorpCM.Models.LoanPiece", b =>
                {
                    b.Property<int>("LoanId");

                    b.Property<int>("PieceId");

                    b.HasKey("LoanId", "PieceId");

                    b.HasIndex("PieceId");

                    b.ToTable("LoanPiece");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<string>("City");

                    b.Property<int?>("CountryId");

                    b.Property<int?>("MuseumId");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("MuseumId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CoraCorpCM.Models.LocationTag", b =>
                {
                    b.Property<int>("LocationId");

                    b.Property<int>("TagId");

                    b.HasKey("LocationId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("LocationTag");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Medium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MuseumId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Museum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address1");

                    b.Property<string>("Address2");

                    b.Property<string>("City");

                    b.Property<int?>("CountryId");

                    b.Property<int?>("LogoId");

                    b.Property<string>("Name");

                    b.Property<int>("RecordCount");

                    b.Property<string>("ShortName");

                    b.Property<string>("State");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("LogoId")
                        .IsUnique()
                        .HasFilter("[LogoId] IS NOT NULL");

                    b.ToTable("Museums");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Origin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<int?>("CountryId");

                    b.Property<int?>("MuseumId");

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("MuseumId");

                    b.ToTable("Origin");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Piece", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessionNumber");

                    b.Property<int?>("AcquisitionId");

                    b.Property<int?>("CollectionId");

                    b.Property<string>("CopyrightOwner");

                    b.Property<int>("CopyrightYear");

                    b.Property<int>("CreationDay");

                    b.Property<int>("CreationMonth");

                    b.Property<int?>("CreationOriginId");

                    b.Property<int>("CreationYear");

                    b.Property<int?>("CurrentLocationId");

                    b.Property<double>("Depth");

                    b.Property<decimal>("EstimatedValue");

                    b.Property<int?>("ExhibitionId");

                    b.Property<int?>("GenreId");

                    b.Property<double>("Height");

                    b.Property<int?>("InsurancePolicyId");

                    b.Property<bool>("IsArchived");

                    b.Property<bool>("IsFramed");

                    b.Property<DateTime>("LastModified");

                    b.Property<string>("LastModifiedById");

                    b.Property<int?>("MediumId");

                    b.Property<int?>("MuseumId");

                    b.Property<int?>("PermanentLocationId");

                    b.Property<int?>("PhotoId");

                    b.Property<int>("RecordNumber");

                    b.Property<int?>("SubgenreId");

                    b.Property<string>("Subject");

                    b.Property<int?>("SubjectMatterId");

                    b.Property<string>("Title");

                    b.Property<int?>("UnitOfMeasureId");

                    b.Property<double>("Width");

                    b.HasKey("Id");

                    b.HasIndex("AcquisitionId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("CreationOriginId");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("ExhibitionId");

                    b.HasIndex("GenreId");

                    b.HasIndex("InsurancePolicyId");

                    b.HasIndex("LastModifiedById");

                    b.HasIndex("MediumId");

                    b.HasIndex("MuseumId");

                    b.HasIndex("PermanentLocationId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("SubgenreId");

                    b.HasIndex("SubjectMatterId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Pieces");
                });

            modelBuilder.Entity("CoraCorpCM.Models.PieceArtist", b =>
                {
                    b.Property<int>("PieceId");

                    b.Property<int>("ArtistId");

                    b.HasKey("PieceId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("PieceArtist");
                });

            modelBuilder.Entity("CoraCorpCM.Models.PieceSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MuseumId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.ToTable("PieceSources");
                });

            modelBuilder.Entity("CoraCorpCM.Models.PieceTag", b =>
                {
                    b.Property<int>("PieceId");

                    b.Property<int>("TagId");

                    b.HasKey("PieceId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PieceTag");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Subgenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MuseumId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.ToTable("Subgenres");
                });

            modelBuilder.Entity("CoraCorpCM.Models.SubjectMatter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MuseumId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.ToTable("SubjectMatters");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("MuseumId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("MuseumId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("CoraCorpCM.Models.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbreviation");

                    b.Property<string>("UnitOfMeasurement");

                    b.HasKey("Id");

                    b.ToTable("UnitsOfMeasure");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Upload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Data");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Upload");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Acquisition", b =>
                {
                    b.HasOne("CoraCorpCM.Models.FundingSource", "FundingSource")
                        .WithMany("Acquisitions")
                        .HasForeignKey("FundingSourceId");

                    b.HasOne("CoraCorpCM.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Acquisitions")
                        .HasForeignKey("MuseumId");

                    b.HasOne("CoraCorpCM.Models.PieceSource", "PieceSource")
                        .WithMany()
                        .HasForeignKey("PieceSourceId");

                    b.HasOne("CoraCorpCM.Models.Upload", "PurchaseReceipt")
                        .WithMany()
                        .HasForeignKey("PurchaseReceiptId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.ApplicationUser", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Users")
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Artist", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Artists")
                        .HasForeignKey("MuseumId");

                    b.HasOne("CoraCorpCM.Models.Origin", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.ArtistGenre", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Artist", "Artist")
                        .WithMany("ArtistGenres")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoraCorpCM.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoraCorpCM.Models.ArtistMedium", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Artist", "Artist")
                        .WithMany("ArtistMedia")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoraCorpCM.Models.Medium", "Medium")
                        .WithMany()
                        .HasForeignKey("MediumId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoraCorpCM.Models.ArtistSubgenre", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Artist", "Artist")
                        .WithMany("ArtistSubgenres")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoraCorpCM.Models.Subgenre", "Subgenre")
                        .WithMany()
                        .HasForeignKey("SubgenreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoraCorpCM.Models.ArtistSubjectMatter", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Artist", "Artist")
                        .WithMany("ArtistSubjectMatters")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoraCorpCM.Models.SubjectMatter", "SubjectMatter")
                        .WithMany("ArtistSubjectMatters")
                        .HasForeignKey("SubjectMatterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoraCorpCM.Models.ArtistTag", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Artist", "Artist")
                        .WithMany("ArtistTags")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoraCorpCM.Models.Tag", "Tag")
                        .WithMany("ArtistTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoraCorpCM.Models.Collection", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Collections")
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Condition", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Conditions")
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Exhibition", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Exhibitions")
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.ExhibitionPiece", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Exhibition", "Exhibition")
                        .WithMany()
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoraCorpCM.Models.Piece", "Piece")
                        .WithMany("ExhibitionPieces")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoraCorpCM.Models.FundingSource", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany()
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Genre", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Genres")
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Inspection", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Condition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId");

                    b.HasOne("CoraCorpCM.Models.Inspector", "Inspector")
                        .WithMany()
                        .HasForeignKey("InspectorId");

                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Inspections")
                        .HasForeignKey("MuseumId");

                    b.HasOne("CoraCorpCM.Models.Piece", "Piece")
                        .WithMany("Inspections")
                        .HasForeignKey("PieceId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Inspector", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Inspectors")
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.InsurancePolicy", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("InsurancePolicies")
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Loan", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Exhibition", "Exhibition")
                        .WithMany()
                        .HasForeignKey("ExhibitionId");

                    b.HasOne("CoraCorpCM.Models.Location", "FromLocation")
                        .WithMany()
                        .HasForeignKey("FromLocationId");

                    b.HasOne("CoraCorpCM.Models.Upload", "LoanAgreement")
                        .WithMany()
                        .HasForeignKey("LoanAgreementId");

                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Loans")
                        .HasForeignKey("MuseumId");

                    b.HasOne("CoraCorpCM.Models.Location", "ToLocation")
                        .WithMany()
                        .HasForeignKey("ToLocationId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.LoanPiece", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Loan", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoraCorpCM.Models.Piece", "Piece")
                        .WithMany("LoanPieces")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoraCorpCM.Models.Location", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Locations")
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.LocationTag", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Location", "Location")
                        .WithMany("LocationTags")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoraCorpCM.Models.Tag", "Tag")
                        .WithMany("LocationTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoraCorpCM.Models.Medium", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Media")
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Museum", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("CoraCorpCM.Models.Upload", "Logo")
                        .WithOne("Museum")
                        .HasForeignKey("CoraCorpCM.Models.Museum", "LogoId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Origin", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany()
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Piece", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Acquisition", "Acquisition")
                        .WithMany("Pieces")
                        .HasForeignKey("AcquisitionId");

                    b.HasOne("CoraCorpCM.Models.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId");

                    b.HasOne("CoraCorpCM.Models.Origin", "CreationOrigin")
                        .WithMany()
                        .HasForeignKey("CreationOriginId");

                    b.HasOne("CoraCorpCM.Models.Location", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId");

                    b.HasOne("CoraCorpCM.Models.Exhibition")
                        .WithMany("Pieces")
                        .HasForeignKey("ExhibitionId");

                    b.HasOne("CoraCorpCM.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId");

                    b.HasOne("CoraCorpCM.Models.InsurancePolicy", "InsurancePolicy")
                        .WithMany()
                        .HasForeignKey("InsurancePolicyId");

                    b.HasOne("CoraCorpCM.Models.ApplicationUser", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.HasOne("CoraCorpCM.Models.Medium", "Medium")
                        .WithMany()
                        .HasForeignKey("MediumId");

                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Pieces")
                        .HasForeignKey("MuseumId");

                    b.HasOne("CoraCorpCM.Models.Location", "PermanentLocation")
                        .WithMany()
                        .HasForeignKey("PermanentLocationId");

                    b.HasOne("CoraCorpCM.Models.Upload", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");

                    b.HasOne("CoraCorpCM.Models.Subgenre", "Subgenre")
                        .WithMany()
                        .HasForeignKey("SubgenreId");

                    b.HasOne("CoraCorpCM.Models.SubjectMatter", "SubjectMatter")
                        .WithMany("Pieces")
                        .HasForeignKey("SubjectMatterId");

                    b.HasOne("CoraCorpCM.Models.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany()
                        .HasForeignKey("UnitOfMeasureId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.PieceArtist", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Artist", "Artist")
                        .WithMany("PieceArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoraCorpCM.Models.Piece", "Piece")
                        .WithMany("PieceArtists")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoraCorpCM.Models.PieceSource", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany()
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.PieceTag", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Piece", "Piece")
                        .WithMany("PieceTags")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoraCorpCM.Models.Tag", "Tag")
                        .WithMany("PieceTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoraCorpCM.Models.Subgenre", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Subgenres")
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.SubjectMatter", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("SubjectMatters")
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("CoraCorpCM.Models.Tag", b =>
                {
                    b.HasOne("CoraCorpCM.Models.Museum", "Museum")
                        .WithMany("Tags")
                        .HasForeignKey("MuseumId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CoraCorpCM.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CoraCorpCM.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoraCorpCM.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CoraCorpCM.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
